# Schema definitions for spin.

# 'path' --> values will be converted to py.path objects

# 'internal' --> settings must not come from a configuration file, can
# only be set internally

# 'usersetting' --> can only(?) be set via a configuration file; it
# would be a bug, if the code does it

# 'list' --> a literal list *or* simply a string that is space-split

minimum-spin:
  type: str internal
  help: |
    The minimal version of spin, that can process this spinfile. This
    property is required.

spin:
  type: object
  help: |
    Settings required for running spin. Many of these cannot be set
    via a spinfile or via the command line, but are computed by spin.
  noindex:
  properties:
    spinfile:
      type: path
      help: |
        The name of the configuration file for the project. This can
        be overriden via 'spin -f <filename>'.
      default: spinfile.yaml
    env_base:
      type: path internal
      help: |
        Where environments are provisioned.
      default: "{SPIN_CACHE}/{spin.project_hash}"
    project_root:
      type: path internal
      help: |
        The absolute path to the project directory.
      default: .spin
    spin_dir:
      type: path internal
      help: |
        The relative path from <project_root> to spin's project
        related data.
      default: .spin
    spin_global:
      type: path internal
      help: |
        User settings that will apply to all projects are read from
        this file.
      default: "{SPIN_CONFIG}/global.yaml"
    spin_global_plugins:
      type: path internal
      default: "{SPIN_CACHE}/plugins"
    plugin_dir:
      type: path internal
      default: "{spin.env_base}/plugins"
    cruise_spin:
      type: path
      default: spin
    index_url:
      type: str
      help: The default Python package index url.
      default: https://packages.contact.de/tools/stable
    extra_index:
      type: str
      help: Additional index to install plugin-packages from.

  # disallow plugins or user setting to write to the 'spin' context to
  # keep sanity
  unknown-properties: false

python:
  requirements:
    type: list usersetting
    help: |
      The list of this project's external Python requirements, that
      have to be installed into the project's virtual
      environment. This excludes requirements stated as
      'install_requires' in setup.py/setup.cfg.

extra-tasks:
  type: object
  help: |
    `extra-tasks` maps task names to task definitions, where task
    definitions support ``env`` and ``script`` keys.

quiet:
  type: boolean
  default: false
  help: |
    Spin normally echos the verbatim commands it runs. When `quiet` is
    set, this output is suppressed. Additionally, some plugins use
    `quiet` to suppress more output of the tools they run.

verbose:
  type: boolean
  default: false
  help: |
    When `verbose` is on, spin outputs additional information, like
    the time spent running tasks. Some plugins use `verbose` to make
    tools more chatty.

hooks:
  type: object
  help: |
    A dictionary mapping workflow names to lists of commands. This is
    automatically set up by the `when` argument to
    :py:func:`spin.task`.

cruise:
  type: object

plugins:
  type: list
  help: |
    The list of plugins to import.

plugin-packages:
  type: list
  help: |
    A list of plugin packages to install. Supports the same
    requirements specifiers as pip, including URLs, local file names
    and PEP 440 specifiers.

platform:
  type: object
  properties:
    exe:
      type: path
    shell:
      type: path
