# Schema definitions for spin.
#
# 'internal'     --> Settings must not come from a configuration file, can only
#                    be set internally. FIXME: That is not implemented.
#
# Attributes with the following types will be converted to specific Python types
# and assigned to the global configuration tree.
#
# 'object'       --> dict/ConfigTree that contains key-values pairs
# 'path'         --> values will be converted Path objects from the path package
# 'list'         --> literal list, i.e. list containing only strings
# 'str'          --> literal/string
# 'float'        --> floating point number
# 'int'          --> integer value
#

spin:
  type: object
  help: |
    Settings required for running spin. Many of these cannot be set
    via a spinfile or via the command line, but are computed by spin.
  properties:
    spinfile:
      type: path
      help: |
        The name of the configuration file for the project. This can
        be overridden via 'spin -f <filename>'.
      default: spinfile.yaml
    project_root:
      type: path internal
      help: The path to the project directory.
      # value is set during runtime
    spin_dir:
      type: path internal
      help: |
        The absolute path to spin's project related data. This is also the place
        environments are provisioned.
      default: "{spin.project_root}/.spin"
    launch_dir:
      type: path internal
      help: The directory in which spin was called.
      # value is set during runtime
    cache:
      type: path
      default: "{SPIN_CACHE}"
      help: Path that points to spins cache
    config:
      type: path internal
      default: "{SPIN_CONFIG}"
      help: Path where to store global configuration for spin
    version:
      type: str internal
      help: The version of cs.spin that is being used.
    project_name:
      type: str internal
      help: The project that is spin running on
    topo_plugins:
      type: list internal
      help: Topological ordered list of initialized plugins
    index_url:
      type: str
      help: The default Python package index url.
      default: https://packages.contact.de/tools/stable
    extra_index:
      type: str
      help: Additional index to install plugin-packages from.
    hooks:
      type: object
      help: |
        A dictionary mapping workflow names to lists of commands. This is
        automatically set up by the `when` argument to :py:func:`spin.task`.
  # FIXME: That was never implemented. Do we want that?
  # Disallow plugins or user setting to write to the 'spin' context to
  # keep sanity.
  unknown-properties: false

environment:
  type: object
  help: |
    `environment` maps additional environment variables and their values which
    will added to the environment when running cs.spin.

extra-tasks:
  type: object
  help: |
    `extra-tasks` maps task names to task definitions, where task
    definitions support ``env`` and ``script`` keys.

quiet:
  type: bool
  default: false
  help: |
    Spin normally echos the verbatim commands it runs. When `quiet` is
    set, this output is suppressed. Additionally, some plugins use
    `quiet` to suppress more output of the tools they run.

verbose:
  type: bool
  default: false
  help: |
    When `verbose` is on, spin outputs additional information, like
    the time spent running tasks. Some plugins use `verbose` to make
    tools more chatty.

plugins:
  type: list
  help: The list of plugins to import.

plugin-packages:
  type: list
  help: |
    A list of plugin packages to install. Supports the same
    requirements specifiers as pip, including URLs, local file names
    and PEP 440 specifiers.

platform:
  type: object
  help: Providing OS/platform-specific properties
  properties:
    exe:
      type: path
      help: The file type of executables, "exe" on Windows and "" on non-Windows
    shell:
      type: path
      help: Reflects the `SHELL` environment variable at cs.spins startup

loaded:
  type: object internal
  help: Mapping between plugin names and their module objects

schema:
  type: object internal
  help: The schema shipped by cs.spin.
