all:
	#pandoc plugin_distribution.md -o plugin_distribution.pdf --variable colorlinks -V geometry:margin=1.5in
	#evince plugin_distribution.pdf &
	pandoc plugin_guideline.md -o plugin_guideline.pdf --variable colorlinks -V geometry:margin=1.5in
	evince plugin_guideline.pdf &
